CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    picture VARCHAR(500),
    google_sub VARCHAR(255) UNIQUE,
    streak_count INTEGER NOT NULL DEFAULT 0,
    last_check_date DATE
);

CREATE TABLE IF NOT EXISTS crops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(20) NOT NULL,
    description TEXT
);

CREATE TABLE IF NOT EXISTS regions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    climate_type VARCHAR(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS crop_stages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crop_id BIGINT NOT NULL REFERENCES crops(id),
    name VARCHAR(150) NOT NULL,
    min_day INTEGER NOT NULL,
    max_day INTEGER NOT NULL,
    description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crop_id BIGINT NULL REFERENCES crops(id),
    stage_id BIGINT NULL REFERENCES crop_stages(id),
    condition VARCHAR(50) NOT NULL,
    type VARCHAR(20) NOT NULL,
    message TEXT NOT NULL,
    priority INTEGER NOT NULL,
    version INTEGER NOT NULL,
    active BOOLEAN NOT NULL,
    region_id BIGINT NULL REFERENCES regions(id)
);

CREATE TABLE IF NOT EXISTS lunar_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phase VARCHAR(50) NOT NULL,
    activity TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS planting_calendar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month INTEGER NOT NULL,
    lunar_phase VARCHAR(50) NOT NULL,
    crop_code VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_crops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    crop_id BIGINT NOT NULL REFERENCES crops(id),
    planting_date DATE NOT NULL,
    water_available BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS growth_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_crop_id BIGINT NOT NULL REFERENCES user_crops(id),
    image_url TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_crop_stage_crop_id ON crop_stages(crop_id);
CREATE INDEX IF NOT EXISTS idx_crop_stage_name ON crop_stages(name);
CREATE INDEX IF NOT EXISTS idx_recommendation_crop_id ON recommendations(crop_id);
CREATE INDEX IF NOT EXISTS idx_recommendation_stage_id ON recommendations(stage_id);
CREATE INDEX IF NOT EXISTS idx_recommendation_condition ON recommendations(condition);
CREATE INDEX IF NOT EXISTS idx_recommendation_lookup ON recommendations(crop_id, stage_id, condition, active, region_id);
CREATE INDEX IF NOT EXISTS idx_user_crop_crop_id ON user_crops(crop_id);
CREATE INDEX IF NOT EXISTS idx_planting_calendar_lookup ON planting_calendar(month, lunar_phase);
